# Generated by Django 5.2.17 on 2026-08-27 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['user', '-updated_at'], name='watch_watch_user_id_d022b6_idx'),
        ),
    ]
