# Generated by Django 5.2.17 on 2026-09-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('watch', '0003_userrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrating',
            name='unique_user_content_rating',
        ),
        migrations.RemoveConstraint(
            model_name='watchprogress',
            name='unique_user_content_watch_progress',
        ),
        migrations.AddField(
            model_name='userrating',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['profile', '-updated_at'], name='watch_watch_profile_24aacd_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user', 'profile', 'tmdb_id', 'media_type'), name='unique_user_profile_content_rating'),
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('user', 'profile', 'tmdb_id', 'media_type', 'season', 'episode'), name='unique_user_profile_content_watch_progress'),
        ),
    ]
