# Generated by Django 5.2.17 on 2026-09-18 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_remove_userrating_unique_user_content_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
