# Generated by Antigravity on 2026-09-18

from django.db import migrations


def align_historical_timestamps(apps, schema_editor):
    WatchProgress = apps.get_model('watch', 'WatchProgress')
    for progress in WatchProgress.objects.all():
        updated = False
        # 1. If created_at > updated_at (erroneously defaulted during migration 0005)
        if progress.created_at and progress.updated_at and progress.created_at > progress.updated_at:
            progress.created_at = progress.updated_at
            updated = True

        # 2. If completed=True and completed_at is None, assign updated_at
        if progress.completed and not progress.completed_at:
            progress.completed_at = progress.updated_at or progress.created_at
            updated = True

        # 3. If completed_at is earlier than created_at
        if progress.completed and progress.completed_at and progress.created_at and progress.completed_at < progress.created_at:
            progress.created_at = progress.completed_at
            updated = True

        if updated:
            progress.save(update_fields=['created_at', 'completed_at'])


def reverse_align(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_watchprogress_completed_at_watchprogress_created_at'),
    ]

    operations = [
        migrations.RunPython(align_historical_timestamps, reverse_align),
    ]
