# Generated by Django 5.2.17 on 2026-08-27 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(default='movie', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.CharField(blank=True, default='', max_length=10)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(default='1080p', max_length=20)),
                ('format', models.CharField(default='mp4', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Download'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('source_provider', models.CharField(default='AutoEmbed Direct', max_length=50)),
                ('temporary_path', models.CharField(blank=True, default='', max_length=500)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
