# Generated by Django 5.2.17 on 2026-09-02 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('playback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playbackserverpreference',
            name='unique_user_media_server_preference',
        ),
        migrations.AddField(
            model_name='playbackserverpreference',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_preferences', to='accounts.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='playbackserverpreference',
            constraint=models.UniqueConstraint(fields=('user', 'profile', 'tmdb_id', 'media_type', 'season', 'episode'), name='unique_user_profile_media_server_preference'),
        ),
    ]
